version: "3.3"
services:
  node-img:
    image: "ghcr.io/atticus6/img-create-master:latest"
    container_name: img-create-master-container
    restart: unless-stopped
    volumes:
      - ./app.js:/app/app.js
    working_dir: /app
    ports:
      - "19000:19000"
    command: node app.js
