version: "3.3"
services:
  node-img:
    image: "img-craete:0.1"
    container_name: blog
    restart: unless-stopped
    volumes:
      - ./app.js:/app/app.js
    working_dir: /app
    ports:
      - "19000:19000"
    command: node app.js
